<table class="table table-bordered table-hover">
                  <thead>
                      <tr>
                          <th>Id</th>
                          <th>Author</th>
                          <th>Comment</th>
                          <th>Article</th>
                          <th>Status</th>
                          <th>Date</th>
                          <th>Approve</th>
                          <th>Unapprove</th>
                          <th>Delete</th>
                      </tr>
                  </thead>
                  <tbody>
                  <?php 
                    showAllComments();
                  ?>
                  </tbody>
              </table>