<table class="table table-bordered table-hover">
                  <thead>
                      <tr>
                          <th>Id</th>
                          <th>Photo</th>
                          <th>Username</th>
                          <th>Firstname</th>
                          <th>Lastname</th>
                          <th>Email</th>
                          <th>Created</th>
                          <th>Role</th>
                      </tr>
                  </thead>
                  <tbody>
                  <?php 
                    showAllUsers();
                  ?>
                  </tbody>
              </table>